# This is a basic workflow to help you get started with Actions

name: time

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '* * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-time:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.email "biningo@yeah.net"
          git config --global user.name "lyer"
      - name: write time
        run: echo '## '$(date) > README.md
      - name: push
        run: |
          git add README.md
          git commit -m "update time"
          git push
